const API_VERSION='2026-07';
const BASE='https://precisionatvfab.com';
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function strip(v=''){return String(v).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
function money(v,c='USD'){try{return new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(Number(v||0))}catch{return '$'+v}}
export default async function handler(req,res){
 const handle=String(req.query.handle||'').trim();const raw=process.env.SHOPIFY_STORE_DOMAIN||'';const domain=raw.replace(/^https?:\/\//,'').replace(/\/$/,'');const token=process.env.SHOPIFY_STOREFRONT_TOKEN||process.env.SHOPIFY_STOREFRONT_ACCESS_TOKEN||process.env.SHOPIFY_STOREFRONT_PUBLIC_ACCESS_TOKEN;
 if(!handle||!domain||!token){res.status(404).send('Collection not found.');return}
 const query=`query Collection($handle:String!){collection(handle:$handle){handle title descriptionHtml seo{title description} image{url altText} products(first:48){nodes{id handle title productType vendor featuredImage{url altText} images(first:1){nodes{url altText}} variants(first:10){nodes{id availableForSale price{amount currencyCode}}}}}}}`;
 try{
  const r=await fetch(`https://${domain}/api/${API_VERSION}/graphql.json`,{method:'POST',headers:{'content-type':'application/json','X-Shopify-Storefront-Access-Token':token},body:JSON.stringify({query,variables:{handle}})});const j=await r.json();const c=j.data?.collection;if(!c){res.status(404).send('Collection not found.');return}
  const canonical=BASE+'/collections/'+c.handle;const title=c.seo?.title||c.title+' | Precision ATV';const desc=c.seo?.description||strip(c.descriptionHtml).slice(0,155)||('Shop '+c.title+' from Precision ATV.');
  const cards=(c.products?.nodes||[]).map(p=>{const v=p.variants?.nodes?.find(x=>x.availableForSale)||p.variants?.nodes?.[0];const image=p.featuredImage?.url||p.images?.nodes?.[0]?.url||'';return `<article class="product"><a class="product-card-link" href="/products/${encodeURIComponent(p.handle)}">${image?`<div class="product-media"><img src="${esc(image)}" alt="${esc(p.featuredImage?.altText||p.title)}"></div>`:'<div class="product-media">PRECISION ATV</div>'}<div class="product-body"><div class="product-type">${esc(p.productType||'Powersports')}</div><div class="product-title">${esc(p.title)}</div><div class="price">${money(v?.price?.amount,v?.price?.currencyCode||'USD')}</div><span class="btn">View details</span></div></a></article>`}).join('');
  const nav=`<div class="navlinks"><a href="/shop">Shop</a><a href="/services">Engine Builds & Tuning</a><a href="/about">About</a><a href="/contact">Contact</a><a class="admin-nav" href="/admin">Admin</a><a class="btn" href="tel:+19362287655">Call the shop</a></div><div class="mobile-actions"><a class="mobile-admin" href="/admin">Admin</a><a class="mobile-call" href="tel:+19362287655">Call</a></div>`;
  const footer=`<div class="policy-links"><a href="/shop">Shop</a><a href="/services">Engine Builds & Tuning</a><a href="/about">About</a><a href="/contact">Contact</a><a href="/admin">Admin</a><a href="https://precisionatv-com.myshopify.com/policies/refund-policy">Returns</a><a href="https://precisionatv-com.myshopify.com/policies/privacy-policy">Privacy</a></div>`;
  res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','public, s-maxage=300, stale-while-revalidate=3600');
  res.status(200).send(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${canonical}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${canonical}"><meta property="og:type" content="website">${c.image?.url?`<meta property="og:image" content="${esc(c.image.url)}">`:''}<link rel="stylesheet" href="/styles.css"></head><body><div class="topbar"><div class="wrap"><div>CONROE, TEXAS • BUILT FOR THE RIDE</div><div><a href="tel:+19362287655">(936) 228-7655</a></div></div></div><nav class="nav"><div class="wrap"><a class="brand" href="/">PRECISION <span>ATV</span></a>${nav}</div></nav><header class="page-hero"><div class="wrap"><div class="kicker">Precision ATV collection</div><h1>${esc(c.title)}</h1></div></header><section><div class="wrap"><div class="collection-copy description">${c.descriptionHtml||'<p>Shop products for this application from Precision ATV.</p>'}</div><div class="product-grid">${cards||'<div class="notice">No products are currently available in this collection.</div>'}</div></div></section><footer class="footer"><div class="wrap footer-grid"><div><div class="brand">PRECISION <span>ATV</span></div><p>1801 N Loop 336 E • Conroe, TX 77301</p></div>${footer}</div></footer><script src="/site.js"></script></body></html>`);
 }catch(e){res.status(500).send('Collection temporarily unavailable.')}
}